### PR TITLE
Readable Cached Artifacts

### LINKED ISSUE #6298: 'hab pkg upload' fails with permission denied when uploading from /hab/cache/artifacts directory
It is a fairly useful scenario to be able to upload packages to a depot from a cached artifact directory (eg /hab/cache/artifacts).  As of 0.78 this fails with a 'permission denied' error because we are writing the downloaded artifacts with a root-only read access.  So a user has to do a 'sudo' in this case.  Also we don't give any indication of which file the permission denied is happening on, so its not super obvious to debug from a users perspective.

We should consider changing the privileges back to what they were prior to 0.78 so we don't require sudo in such cases.  The installed packages themselves are fully world readable, just the artifact is locked down.

This is a side effect of this change - https://github.com/habitat-sh/habitat/pull/5803#issuecomment-465790809

### PR DESCRIPTION
**Pull request by christophermaier**
This addresses #6298, building off the work @stevendanna did in #7489. In particular, it ensures that installing packages yields cached artifacts that are world readable, rather than only readable by root, on Unix systems.

It introduces `habitat_core::fs::Permissions`, a new `Option`-like type abstraction over platform-specific permission representations and makes the setting of these permissions explicit in function type signatures. Though the `download` function in our API client is used to download multiple things from Builder, this change only affects package artifacts; permissions for public and private origin keys, as well as public origin encryption keys, are _not_ manipulated at all. 

Note that these permission changes apply to _all_ artifacts that are downloaded, regardless of where they are downloaded to, or by whom.

This new `Permissions` type is now used by `AtomicWriter`, and (by extension) everything that calls it. It may prove useful for other permission-related operations elsewhere in the codebase, but that work is not attempted here.

Fixes #6298

### CODE REVIEW

File: components/builder-api-client/src/builder.rs [hunk 1]
```diff
@@ -90,6 +92,24 @@ mod json_u64 {
...
+    /// they are "normally" set to when they are created. Here,
+    /// "normal" denotes the low-level programming library sense,
+    /// rather than any particular domain-specific sense.
+    Standard,
+    /// Indicates that a file should be created with very specific
+    /// permissions.
+    #[cfg(windows)]
+    Explicit(Vec<win_perm::PermissionEntry>),
+    #[cfg(not(windows))]
+    Explicit(u32),
```
Comment (davidMcneil) [inline components/builder-api-client/src/builder.rs]: Wonder if it is worth using [`std::fs::Permissions`](https://doc.rust-lang.org/stable/std/fs/struct.Permissions.html) here? It looks like it is really just a thin wrapper around a `u32` so maybe it does not buy us much. Probably fine either way.

File: components/builder-api-client/src/builder.rs [hunk 2]
```diff
@@ -186,7 +207,13 @@ impl BuilderAPIClient {
         fs::create_dir_all(&dst_path)?;
         let file_name = response::get_header(&resp, X_FILENAME)?;
         let dst_file_path = dst_path.join(file_name);
-        let w = AtomicWriter::new(&dst_file_path)?;
+        let w = {
+            let mut w = AtomicWriter::new(&dst_file_path)?;
+            if let Permissions::Explicit(permissions) = permissions {
```
Comment (davidMcneil) [inline components/builder-api-client/src/builder.rs]: > To make further distinctions would be tricky and a bit more complicated.

Is this where you would make that distinction? Essentially, only add the explicit permissions if it is the `/hab/cache/artifacts` directory.

**Comment by mwrock** [comment]
This seems like a sound approach to me. I really don't see a problem with making artifacts universally world readable. Perhaps if a user ever became concerned with that they could `chmod` it after download.

File: components/builder-api-client/src/builder.rs (hunk 2 above)
Comment (christophermaier) [reply components/builder-api-client/src/builder.rs]: It's not that it's impossible, it's just that it would be a bit messy and would end up distributing filesystem awareness in various parts of the codebase.

File: components/builder-api-client/src/builder.rs (hunk 1 above)
Comment (christophermaier) [reply components/builder-api-client/src/builder.rs]: Yeah, I don't think that really buys us much at all; we'd still need some additional abstraction on top of that to deal with Windows stuff the way we would want to.

The main thing this type really does is provide a richer, permission-specific `Option` for us to use (as well as a facade behind which to hide all the platform-specific differences). I felt it was much better to have function signatures like 
```
do_something(..., Permissions::Standard, ...)
``` 

than

```
do_something(..., None, ...)
```

Comment (davidMcneil) [reply components/builder-api-client/src/builder.rs]: I was not very clear. I definitely like the `Option` like wrapper. I was saying the enum could become:
```rust
pub enum Permissions {
    Standard,
    #[cfg(windows)]
    Explicit(Vec<win_perm::PermissionEntry>),
    #[cfg(not(windows))]
    Explicit(std::fs::Permissions),
}
```

File: components/builder-api-client/src/builder.rs [hunk 3]
```diff
@@ -186,7 +189,11 @@ impl BuilderAPIClient {
         fs::create_dir_all(&dst_path)?;
         let file_name = response::get_header(&resp, X_FILENAME)?;
         let dst_file_path = dst_path.join(file_name);
-        let w = AtomicWriter::new(&dst_file_path)?;
+        let w = {
+            let mut w = AtomicWriter::new(&dst_file_path)?;
+            w.with_permissions(permissions);
+            w
+        };
```
Comment (davidMcneil) [inline components/builder-api-client/src/builder.rs]: This could be slightly shortned to:
```rust
let mut w = AtomicWriter::new(&dst_file_path)?;
w.with_permissions(permissions);
let w = w;
```

Should `with_permissions` be a constructor? Which avoids the need for `w` ever being mutable.

File: components/core/src/fs.rs [hunk 4]
```diff
@@ -712,21 +746,14 @@ impl AtomicWriter {
...
-    pub fn with_permissions(&mut self, mode: u32) { self.permission = Some(mode); }
-
-    #[cfg(windows)]
-    /// with_permission sets given permissions on the destination path.
-    pub fn with_permissions(&mut self, entries: Vec<win_perm::PermissionEntry>) {
-        self.permission = Some(entries);
-    }
+    /// Note: On Unix platforms, permissions are set explicitly and
+    /// not subject to the process umask.
+    pub fn with_permissions(&mut self, permissions: Permissions) { self.permissions = permissions; }
```
Comment (davidMcneil) [inline components/core/src/fs.rs]: What would you think about making this a constructor?

File: components/builder-api-client/src/builder.rs (hunk 3 above)
Comment (christophermaier) [reply components/builder-api-client/src/builder.rs]: I kinda want `AtomicWriter` to be created with a Builder pattern, but that's a whole bunch of extra code to write.

A constructor might be a nice compromise. I'll play with it.

Comment (stevendanna) [reply components/builder-api-client/src/builder.rs]: I agree that a builder pattern might be nice.  I held off just because it felt silly with a single method, but if we ever get to 2 methods, then I think moving it to the builder pattern would be nice.

File: components/core/src/fs.rs [hunk 5]
```diff
@@ -57,6 +57,43 @@ pub const USER_CONFIG_FILE: &str = "user.toml";
...
+/// Permissions applied to artifacts that are downloaded and/or
+/// cached. On Windows, we don't need do to anything particularly
+/// special, since artifacts will generally inherit the permissions of
+/// their containing directory.
+#[cfg(windows)]
+pub const DEFAULT_CACHED_ARTIFACT_PERMISSIONS: Permissions = Permissions::Standard;
+
+/// An `Option`-like abstraction over platform-specific ways to model
+/// file permissions.
+pub enum Permissions {
```
Comment (stevendanna) [inline components/core/src/fs.rs]: A+ 💯

File: components/builder-api-client/src/builder.rs (hunk 1 above)
Comment (christophermaier) [reply components/builder-api-client/src/builder.rs]: ah, I see what you meant :smile:

File: components/sup/src/manager/service/supervisor.rs [hunk 6]
```diff
@@ -266,7 +266,7 @@ impl Supervisor {
                 // already allow broad reading of the PID file.
                 const PIDFILE_PERMISSIONS: u32 = 0o644;
                 let mut w = fs::AtomicWriter::new(pid_file)?;
-                w.with_permissions(PIDFILE_PERMISSIONS);
+                w.with_permissions(fs::Permissions::Explicit(PIDFILE_PERMISSIONS));
```
Comment (stevendanna) [inline components/sup/src/manager/service/supervisor.rs]: If we wanted we could move the platform conditionality just around the definition of the pidfile permissions now that we have your nice abstraction.

File: components/core/src/fs.rs (hunk 4 above)
Comment (christophermaier) [reply components/core/src/fs.rs]: Yup! Handled in https://github.com/habitat-sh/habitat/pull/7545/commits/a63b8a0577fcc27dea88b67befe917c51dfd790c

File: components/builder-api-client/src/builder.rs (hunk 3 above)
Comment (christophermaier) [reply components/builder-api-client/src/builder.rs]: Worked out pretty nicely: https://github.com/habitat-sh/habitat/pull/7545/commits/a63b8a0577fcc27dea88b67befe917c51dfd790c

File: components/sup/src/manager/service/supervisor.rs (hunk 6 above)
Comment (christophermaier) [reply components/sup/src/manager/service/supervisor.rs]: Good call! Addressed in https://github.com/habitat-sh/habitat/pull/7545/commits/4379e7d7b350fdf216d2670dd71a569b1ca42c40
