### PR TITLE
windows defaults to local studio

### LINKED ISSUE #5464: Local studios should be the default on Windows
Currently the default `hab studio` behavior is to spawn a container which may not work especially on older OSs that cannot run docker. We should make the current local `hab studio -w` the default (no more `-w`) and make container studios explicit via an arg.

### PR DESCRIPTION
**Pull request by mwrock**
Fixes #5464

This makes the local studio the default on Windows. To run a dockerized container, `-D` must be passed. This applies to both `hab studio` and `hab pkg build` commands.

For now, we will still honor `-w` but state that it is deprecated and emit a warning when it is used. We will alo emit a warning when entering the studio without `-w` or `-D` that advises how to enter a dockerized studio (the former default).

Signed-off-by: mwrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

File: components/studio/bin/hab-studio.sh [hunk 1]
```diff
@@ -84,8 +84,8 @@ COMMON FLAGS:
     -q  Prints less output for better use in scripts
     -v  Prints more verbose output
     -V  Prints version information
-    -D  Use a Docker Studio instead of a chroot Studio (only available on Linux)
-    -w  Use a Windows Studio instead of a Docker Studio (only available on Windows)
+    -D  Use a Docker Studio instead of a chroot Studio
+    -w  Use a Windows Studio instead of a Docker Studio (DEPRECATED)
```
Comment (christophermaier) [inline components/studio/bin/hab-studio.sh]: This is a Bash file... why are Windows-only options mentioned in here in the first place? 🤔

File: components/studio/bin/hab-studio.ps1 [hunk 2]
```diff
@@ -66,7 +67,8 @@ COMMON FLAGS:
     -n  Do not mount the source path into the Studio (default: mount the path)
     -q  Prints less output for better use in scripts
     -v  Prints more verbose output
-    -w  Use a Windows studio instead of a Docker Studio (only available on windows)
+    -D  Use a Docker Studio instead of a native Studio
+    -w  Use a Windows studio instead of a Docker Studio (DEPRECATED)
```
Comment (christophermaier) [inline components/studio/bin/hab-studio.ps1]: Might be nice to indicate that it's just the _flag_ that's deprecated, and not the use of a Windows studio itself.

File: components/hab/src/command/studio/enter.rs [hunk 3]
```diff
@@ -240,13 +240,20 @@ mod inner {
...
         }
 
+        for arg in args.iter() {
+            let str_arg = arg.to_string_lossy();
+            if str_arg == String::from("-D") {
+                return false;
+            }
+        }
+
         for arg in args.iter() {
```
Comment (christophermaier) [inline components/hab/src/command/studio/enter.rs]: A comment to point out that this particular chunk of code is in support of a deprecated flag, and thus fair-game for removal soon would be helpful.

File: components/hab/src/command/studio/enter.rs [hunk 4]
```diff
@@ -240,13 +240,20 @@ mod inner {
             return false;
         }
 
+        for arg in args.iter() {
+            let str_arg = arg.to_string_lossy();
+            if str_arg == String::from("-D") {
+                return false;
+            }
+        }
+
```
Comment (baumanj) [inline components/hab/src/command/studio/enter.rs]: Since this is nearly identical to the next block, I think it could be better simplified to:
```rust
        for arg in args.iter() {
            match arg.to_str().unwrap_or("") {
                "-D" => return false,
                "-w" | "--windows" => return true,
                _ => (),
            }
        }
```
This also avoids the need for as many objects to be created by using `&str`s instead of `String`s.

There is one small change here, the conversion to lower case is removed, but I think that's actually incorrect; `-W` (currently unused) shouldn't necessarily be treated the same as `-w`. Also, I don't see anywhere that `--windows` is a documented option, so I think we should either remove that or document it.

File: components/hab/src/cli.rs [hunk 5]
```diff
@@ -687,8 +687,8 @@ fn sub_pkg_build() -> App<'static, 'static> {
         (@arg SRC_PATH: -s --src +takes_value
             "Sets the source path (default: $PWD)")
         (@arg PLAN_CONTEXT: +required +takes_value
-            "A directory containing a `plan.sh` file \
-            or a `habitat/` directory which contains the `plan.sh` file")
+            "A directory containing a `plan.sh` or `plan.ps1` file \
```
[the remark this answers is not in the document]
Comment (christophermaier) [reply components/hab/src/cli.rs]: I really like this ☝️

File: components/studio/bin/hab-studio.sh (hunk 1 above)
Comment (mwrock) [reply components/studio/bin/hab-studio.sh]: Leftover from when there was no windows docker studio and this was the best way to tell people using the linux docker studio on a windows host how to open a windows studio. I'm just gonna remove this.

File: components/hab/src/command/studio/enter.rs (hunk 4 above)
Comment (mwrock) [reply components/hab/src/command/studio/enter.rs]: `--windows` comes from `hab pkg build` which forwards to here. I had thought about doing what you suggest above but my concern was if someone included both flags. I know thats an edge case and technically erroneous but the `-D` flag should trump.
