### PR TITLE
windows-service improvements

### LINKED ISSUE #6375: Hab sup term doesn't stop supervisor on Windows
Issue:

Running `hab sup term` on Windows doesn't appear to do anything.

OS Name:      Microsoft Windows Server 2016 Datacenter
OS Version:   10.0.14393 N/A Build 14393
Hab Version:  hab 0.78.0/20190313120028

Replication:
```
PS > $env:RUST_LOG="debug";$env:RUST_BACKTRACE=1;hab sup term
```

Output:
```
[2019-04-04T12:57:16Z DEBUG habitat_common::ui] UI { shell: Shell { input: InputStream { isatty: true }, out: OutputStream { coloring: Auto, isatty: true }, err: OutputStream { coloring: Auto, isatty: true } } }
[2019-04-04T12:57:16Z DEBUG habitat_core::os::process::imp] Calling child process: ("C:\\hab\\pkgs\\core\\hab-sup\\0.78.0\\20190313123218\\bin\\hab-sup.EXE") ["term"]
[2019-04-04T12:57:16Z DEBUG habitat_core::os::process::imp] sending no-op(windows) signal 0 to pid 744
[2019-04-04T12:57:16Z DEBUG hab_sup] start() returned Ok(()); Exiting 0
```

After running `hab sup term`, there are still running hab processes:
```
PS C:\Users\labadmin\hab_plans> Get-Process -ProcessName hab*

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    110       8     1820       7080       0.00   8276   2 hab
     61       6     1804       5896       0.50    744   2 hab-launch
    207      25     8276      17340       0.27   4700   2 hab-sup
```

Desired Behavior:
`hab sup term` should instruct all running services to gracefully shutdown, run any `post-stop` hooks, remove any PID references, then shut down the hab processes.

### LINKED ISSUE #7417: windows-service may not use latest launcher
The Windows-Service is using an alpha sort to determine the latest version. So, for example, if version 9945 is installed, it will choose that version over 13013 (the current latest). We should templatize things so that it pulls the exact version that the package was built with.

### PR DESCRIPTION
**Pull request by mwrock**
This addresses two key issues:

* Wait for the supervisor to exit before stopping the service upon launcher termination. If someone forcefully kills the launcher process or issues a `hab sup term`, the exit handler for the launcher is fired which immediately shuts down the service and prevents the supervisor from cleanly stopping any running services. So this fully resolves #6375 
* It fixes #7417 by running the launcher in the packages dependency.

Additionally this fixes a small messaging issue that a user recently brought to my attention.

### CODE REVIEW

**Comment by mwrock** [comment]
⚠️ I have found a bug in rendering the launcher path ⚠️ 

Seems tou cannot put a PR into draft mode after it is in non-draft mode...bummer

File: components/windows-service/HabService.cs [hunk 1]
```diff
@@ -184,6 +185,16 @@ private void SupErrorHandler(object sender, DataReceivedEventArgs e)
         private void ExitHandler(object sender, System.EventArgs e)
         {
             log.Error(String.Format("Habitat Supervisor has exited with exit code {0}", proc.ExitCode));
+            var mos = new ManagementObjectSearcher("SELECT ProcessId FROM Win32_Process WHERE Name='hab-sup.exe' AND ParentProcessId=" + proc.Id);
```
Comment (christophermaier) [inline components/windows-service/HabService.cs]: Wait, you get to search for processes _using SQL_?!

Comment (mwrock) [reply components/windows-service/HabService.cs]: everything is a database!

File: components/windows-service/HabService.cs [hunk 2]
```diff
@@ -151,21 +151,11 @@ private static string LauncherPath
                 }
                 else
                 {
-                    // because we declare hab-launcher as a runtime dep
-                    // this path should exist
-                    string launcherBase = Path.Combine(Path.GetPathRoot(Environment.SystemDirectory), "hab\\pkgs\\core\\hab-launcher");
-                    string latestLauncher = LastDirectory(LastDirectory(launcherBase));
-                    return Path.Combine(latestLauncher, "bin\\hab-launch.exe");
+                    return Path.Combine(Path.GetPathRoot(Environment.SystemDirectory), @"%%LAUNCHER_PATH%%", "bin\\hab-launch.exe");
```
[the remark this answers is not in the document]
Comment (mwrock) [reply components/windows-service/HabService.cs]: I just pushed a change so that the C# always pulls the launcher path from the service config file. The `install` hook injects the correct launcher path into that config.
