### PR TITLE
 studio run should not be interactive

### LINKED ISSUE #5289: Windows `hab studio run` runs interactively
On windows, running `hab studio run '<command>'` runs interactively, which causes problems when run via CI systems like concourse. Running `hab studio run '<command'` directly on windows behaves like it is non-interactive in that the command runs and then exits, however it seems as far as powershell/hab is concerned, it is interactive. When attempting to run the above command via Concourse, I receive the following error:

`the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'`

Running a `hab pkg build` goes through without issue. However, I am using `hab studio run` as I need to do some setup prior to the build, such as installing some locally built packages that are dependencies. I would expect `hab pkg build` and `hab studio run` to behave similarly.

### LINKED ISSUE #5459: All `hab studio` commands enter the studio interactively
Instead of getting the usage instructions, it enters the studio. This also happens for `hab studio run ...` commands which breaks our automation.

Habitat 0.61.0 on macOS. Regression since 0.59.0.

```
$ RUST_LOG=debug RUST_BACKTRACE=1 hab studio --help
DEBUG 2018-08-16T00:25:13Z: habitat_common::ui: UI { shell: Shell { input: InputStream { isatty: true }, out: OutputStream { coloring: Auto, isatty: true, is_colored(): true, supports_color(): true }, err: OutputStream { coloring: Auto, isatty: true, is_colored(): true, supports_color(): true } } }
DEBUG 2018-08-16T00:25:13Z: hab::command::studio::enter: Setting HAB_CACHE_KEY_PATH=/Users/jbasch/.hab/cache/keys
DEBUG 2018-08-16T00:25:13Z: hab::command::studio::enter: Setting ARTIFACT_PATH=/Users/jbasch/.hab/cache/artifacts
DEBUG 2018-08-16T00:25:13Z: hab::command::studio::docker: Running command: "/usr/local/bin/docker" "version" "--format=\'{{.Server.Os}}\'"
DEBUG 2018-08-16T00:25:14Z: hab::command::studio::docker: Running command: "/usr/local/bin/docker" "images" "habitat/default-studio:0.61.0" "-q"
DEBUG 2018-08-16T00:25:14Z: hab::command::studio::docker: Found Studio Docker image locally.
DEBUG 2018-08-16T00:25:14Z: hab::command::studio::docker: Running command: "/usr/local/bin/docker" "version" "--format=\'{{.Server.Os}}\'"
DEBUG 2018-08-16T00:25:14Z: hab::command::studio::docker: Running command: "/usr/local/bin/docker" "version" "--format=\'{{.Server.Os}}\'"
DEBUG 2018-08-16T00:25:14Z: hab::command::studio::docker: Running command: "/usr/local/bin/docker" "version" "--format=\'{{.Server.Os}}\'"
DEBUG 2018-08-16T00:25:14Z: hab::command::studio::docker: Running command: "/usr/local/bin/docker" "version" "--format=\'{{.Server.Os}}\'"
DEBUG 2018-08-16T00:25:16Z: habitat_core::os::process::imp: Calling execvp(): ("/usr/local/bin/docker") ["start", "--interactive", "Users--jbasch"]
   hab-studio: No secret keys imported! Did you mean to set HAB_ORIGIN?
To specify a HAB_ORIGIN, either set the HAB_ORIGIN environment
variable to your origin name or run 'hab setup' and specify a
default origin.
   hab-studio: Exported: HAB_AUTH_TOKEN=[redacted]
   hab-studio: Exported: HAB_ORIGIN=[redacted]
   hab-studio: Exported: HAB_BLDR_URL=[redacted]
--> Detected and loading /src/.studiorc

--> Launching the Habitat Supervisor in the background...
    Running: hab sup run
    * Use 'hab svc start' & 'hab svc stop' to start and stop services
    * Use 'sup-log' to tail the Supervisor's output (Ctrl+c to stop)
    * Use 'sup-term' to terminate the Supervisor
    * To pass custom arguments to run the Supervisor, export
      'HAB_STUDIO_SUP' with the arguments before running
      'hab studio enter'.

--> To prevent a Supervisor from running automatically in your
    Studio, export 'HAB_STUDIO_SUP=false' before running
    'hab studio enter'.

[1][default:/src:0]#
```

Environment (outside of studio):
```
HAB_ORIGIN=[redacted]
HAB_BLDR_URL=[redacted]
```

### PR DESCRIPTION
**Pull request by mwrock**
This partially fixes #5459 and also fixes #5289. Note that while 5289 is directed at Windows, it is an issue for linux containers as well. We currently ensure that `pkg build` does not add `--tty` or `--interactive` and this adds the same for `studio run`.

Also, this includes a fix for Windows local `studio run` commands (run with `-w`). The local windows studio run was utterly broken previously.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by elliott-davis** [comment]
I'm working on alternative fix for this but got clobbered by goalie work today. I can push up a wip branch in the morning but I'd like to talk through this before merging

**Comment by mwrock** [comment]
sure thing @elliott-davis

**Comment by baumanj** [comment]
Should we hold off on reviewing this for now? If so, can we (possibly temporarily) close this PR?

**Comment by mwrock** [comment]
In going to change it to remove the ephemeral influenceing parts

**Comment by mwrock** [comment]
ok @elliott-davis I just removed everything that was related to ephemeral containers and will yield to your work there. So this just keeps `run` noninteractive.

File: components/hab/src/command/studio/docker.rs [hunk 1]
```diff
@@ -278,7 +278,7 @@ where
     cmd_args.push("--name".into());
     cmd_args.push(name.into());
     match args.first().map(|f| f.to_str().unwrap_or_default()) {
-        Some("build") => {}
+        Some("build") | Some("run") => {}
```
Comment (baumanj) [inline components/hab/src/command/studio/docker.rs]: This was already broken, but these cases won't match if the `hab studio` command uses the aliases that are allowed for `build` (`b`, `bu`, `bui`, `buil`) and `run` (`r`, `ru`).

As long as we're changing code, this might be a good time to just take those aliases out.

Comment (mwrock) [reply components/hab/src/command/studio/docker.rs]: ok. removed.

Comment (baumanj) [reply components/hab/src/command/studio/docker.rs]: Ooh, I love it when our UX gets better
