### PR TITLE
[sup,hab] Add back `hap-sup config` subcommand.

### LINKED ISSUE #1729: display the config for a package that does not have configuration, a bad error message is displayed
This can be emulated with the following commands

```
[chef@ip-172-31-18-110 ~]$ sudo -E hab pkg install  core/logstash
» Installing core/logstash
→ Using core/logstash/5.1.1/20161221223434
★ Install of core/logstash/5.1.1/20161221223434 complete with 0 new packages installed.
[chef@ip-172-31-18-110 ~]$ sudo -E hab sup config  core/logstash
hab-sup(ER)[src/error.rs:372:8]: No such file or directory (os error 2)
```

Hello - thanks for reporting an issue with Habitat.

In order to help us troubleshoot the issue, please be sure to include the following information if applicable:

- [ ] The OS (including version) where you are running any of the Habitat commands.
Centos 7.2
- [ ] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

```
RUST_LOG=debug RUST_BACKTRACE=1 hab sup config  core/logstash
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_core::os::process::imp: Calling execvp(): ("/hab/pkgs/core/hab-sup/0.16.0/20170119213934/bin/hab-sup") ["config", "core/logstash"]
DEBUG:hab_sup: clap matches ArgMatches { args: {}, subcommand: Some(SubCommand { name: "config", matches: ArgMatches { args: {"pkg_ident_or_artifact": MatchedArg { occurs: 1, vals: {1: "core/logstash"} }}, subcommand: None, usage: Some("USAGE:\n    hab-sup config [FLAGS] <pkg_ident_or_artifact>") } }), usage: Some("USAGE:\n    hab-sup [FLAGS] [SUBCOMMAND]") }
DEBUG:hab_sup: subcommand name "config"
DEBUG:hab_sup: Subcommand matches ArgMatches { args: {"pkg_ident_or_artifact": MatchedArg { occurs: 1, vals: {1: "core/logstash"} }}, subcommand: None, usage: Some("USAGE:\n    hab-sup config [FLAGS] <pkg_ident_or_artifact>") }
DEBUG:hab_sup: Config:
Config { http_listen_addr: ListenAddr(V4(0.0.0.0:9631)), gossip_listen: GossipListenAddr(V4(0.0.0.0:9638)), command: Config, package: PackageIdent { origin: "core", name: "logstash", version: None, release: None }, local_artifact: None, url: "https://willem.habitat.sh/v1/depot", topology: Standalone, group: "default", path: "/hab/svc/hab-sup/data", archive: "", bind: [], key: "", email: None, expire_days: None, userkey: None, servicekey: None, infile: None, outfile: None, gossip_peer: [], gossip_permanent: false, update_strategy: None, service_group: "", file_path: "", version_number: 0, organization: None, ring: None, config_from: None }
hab-sup(ER)[src/error.rs:372:8]: No such file or directory (os error 2)		
```

- [ ] Current Habitat environment variables where the `hab` command or supervisor is running.  These can be gathered using:

		env | grep HAB | grep -v HAB_AUTH_TOKEN

(no environment is present - this command returns nothing)

### PR DESCRIPTION
**Pull request by fnichol**
This change restores the Supervisor's `config` subcommand to preserve
the behavior of the Supervisor in constrained environments, such as
in containers.

Additionally, in the event that the desired package does not have a
`default.toml`, a message explaining this will be printed to the
standard error stream rather than the standard output stream to help
with programs or scripts which may consume the raw TOML data.

References #1689
Fixes #1729

Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

File: components/common/src/command/package/config.rs [hunk 1]
```diff
@@ -30,11 +31,19 @@ use toml;
 
 use error::Result;
 
-pub fn start(ident: &PackageIdent, fs_root_path: &Path) -> Result<()> {
-    let package = try!(PackageInstall::load(ident, Some(fs_root_path)));
+pub fn start<P: ?Sized>(ident: &PackageIdent, fs_root_path: &P) -> Result<()>
```
Comment (reset) [inline components/common/src/command/package/config.rs]: You actually don't need to take a reference on `P` here since you're asking for P to implement the trait `AsRef<Path>`. You can just pass `Some(fs_root_path.as_ref())` to `PackageInstall::load` and you're good to go!

File: components/sup/src/main.rs [hunk 2]
```diff
@@ -132,6 +140,13 @@ fn sub_bash(m: &ArgMatches) -> Result<()> {
     command::shell::bash()
 }
 
+fn sub_config(m: &ArgMatches) -> Result<()> {
+    let ident = try!(PackageIdent::from_str(m.value_of("PKG_IDENT").unwrap()));
+
+    try!(common::command::package::config::start(&ident, Path::new("/")));
```
Comment (reset) [inline components/sup/src/main.rs]: Since you're using `AsRef<Path>` on `config::start()` you can actually just pass `"/"` instead of `Path::new("/")` 😄

File: components/common/src/command/package/config.rs (hunk 1 above)
Comment (fnichol) [inline components/common/src/command/package/config.rs]: Whoops, copy-pasta leftover there, from past-self.

File: components/sup/src/main.rs (hunk 2 above)
Comment (fnichol) [inline components/sup/src/main.rs]: Ha, that's why I changed the signature of the function, doh!.

**Comment by reset** [comment]
gif-keyboard-2738520676966543065
