### PR TITLE
only install alternate channel backline in CI

### LINKED ISSUE #4371: HAB_BLDR_CHANNEL and "Package not found" / builder builds working currently?
Since earlier this week, we encounter the following early error when building packages:

```
worker.1    | _ The package does not have any versions in the specified channel.                                                                                              
worker.1    | _ Did you intend to install one of the folowing instead?                                                                                                        
worker.1    | _   core/hab-backline/0.51.0/20171219022621 in channel stable                                                                                                   
worker.1    | _   core/hab-backline/0.51.0/20171219022621 in channel unstable                                                                                                 
worker.1    | ___                                                                                                                                                             
worker.1    | ___ Package not found                                                                                                                                           
worker.1    | ___ 
worker.1    | DEBUG:habitat_builder_worker::runner::studio: completed studio build command, status=ExitStatus(ExitStatus(256))
```

This seems to be because builder attempts to install the packages from a channel custom to the build (`bldr-877267041537662976`):

```
worker.1    | DEBUG:habitat_builder_worker::runner::studio: setting studio build command env, HAB_BLDR_CHANNEL=bldr-877267041537662976
[...]
worker.1    | DEBUG:habitat_http_client::api_client: GET http://localhost:9636/v1/depot/channels/core/bldr-877267041537662976/pkgs/hab-backline/0.51.0/latest with ApiClient { endpoint: "http://localhost:9636/v1", inner: Client { redirect_policy: FollowAll, read_timeout: Some(Duration { secs: 60, nanos: 0 }), write_timeout: Some(Duration { secs: 6
0, nanos: 0 }), proxy: None }, proxy: None, target_scheme: "http", user_agent_header: UserAgent("hab/0.51.0/20171219021329 (x86_64-linux; 4.10.0-19-generic)") }
[...]
```

On Slack we were pointed to https://github.com/habitat-sh/habitat/pull/4289/files#diff-98ec64e3f381a5ccde4f4506db6aae9cL206 - reverting that particular line or explicitly setting it to stable (like below) doesn't seem to make a difference though:

```
diff --git a/components/studio/libexec/hab-studio-type-default.sh b/components/studio/libexec/hab-studio-type-default.sh
index 0682aeb5e..3dc9bb50f 100644
--- a/components/studio/libexec/hab-studio-type-default.sh
+++ b/components/studio/libexec/hab-studio-type-default.sh
@@ -203,7 +203,7 @@ PROFILE_ENTER
 
 _hab() {
   # We remove a couple of env vars we do not want for this instance of the studio
-  $bb env FS_ROOT=$HAB_STUDIO_ROOT HAB_CACHE_KEY_PATH= $hab $*
+  $bb env FS_ROOT=$HAB_STUDIO_ROOT HAB_CACHE_KEY_PATH= HAB_BLDR_CHANNEL=stable $hab $*
 }
 
 _pkgpath_for() {
```

Any ideas what could be wrong / have changed?

I currently test on top of latest master, https://github.com/habitat-sh/habitat/commit/79ff23433081234745b69a85c6fceeddf1931f52, with https://github.com/kinvolk/habitat/tree/schu/vagrant

Thanks.

### PR DESCRIPTION
**Pull request by mwrock**
fixes #4371 

This reverts the usage of the `HAB_BLDR_CHANNEL` hen pulling down a studio backline and instead introduces a `CI_OVERRIDE_CHANNEL` used only in releases to overide the channel used when pulling backline.

Signed-off-by: mwrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

File: components/studio/libexec/hab-studio-type-default.sh [hunk 1]
```diff
@@ -66,10 +66,32 @@ finish_setup() {
...
+  # easy to create an unstable studio.)
   for pkg in $pkgs; do
-    _hab install $pkg
+    if [[ -n "${CI_OVERRIDE_CHANNEL:-}" ]]; then
+      info "Override channel set; retrieving ${pkg} from ${CI_OVERRIDE_CHANNEL}"
+      _hab install --channel="${CI_OVERRIDE_CHANNEL}" ${pkg} || {
+        info "Package not found in ${CI_OVERRIDE_CHANNEL}; falling back to stable"
+        _hab install ${pkg}
+      }
+    else
```
Comment (baumanj) [inline components/studio/libexec/hab-studio-type-default.sh]: Just personal preference, but I'd find this a bit more readable:
```bash
if _hab install --channel="${CI_OVERRIDE_CHANNEL}" ${pkg}; then
    info "Override channel set; installed ${pkg} from ${CI_OVERRIDE_CHANNEL}"
else
    info "Package not found in ${CI_OVERRIDE_CHANNEL}; falling back to stable"
    _hab install ${pkg}
fi
```

**Comment by mwrock** [comment]
addressed your comment @baumanj thanks!

**Comment by schu** [comment]
I tried to test this in a fresh Vagrant VM and see the following error:

```
worker.1    | /hab/pkgs/core/hab-studio/0.51.0/20171219022721/bin/hab-studio: 84: /hab/pkgs/core/hab-studio/0.51.0/20171219022721/bin/hab-studio: CI_OVERRIDE_CHANNEL: parameter not set
worker.1    | DEBUG:habitat_builder_worker::runner::studio: completed studio build command, status=ExitStatus(ExitStatus(512))
```

`bin/hab-studio` has `nounset` set and does source `hab-studio-type-default.sh`. Adding

```
CI_OVERRIDE_CHANNEL="${CI_OVERRIDE_CHANNEL:-}"
```

on top of `hab-studio-type-default.sh` does fix the issue. How does it work without?

To test, I'm using https://github.com/habitat-sh/habitat/pull/4161 + the changes from this pull request + a manually updated `hab-studio-type-default.sh`; on my box I do:

```
cp components/studio/libexec/hab-studio-type-default.sh /hab/pkgs/core/hab-studio/0.51.0/20171219022721/libexec/hab-studio-type-default.sh
```

File: components/studio/libexec/hab-studio-type-default.sh [hunk 2]
```diff
@@ -66,10 +66,28 @@ finish_setup() {
...
+  #
+  # If you're not on the Habitat core team, you will likely never need
+  # this, or even have to know it exists.
+  #
+  # (This is also why we're not using HAB_BLDR_CHANNEL for this and
+  # replicating the fallback logic from hab-plan-build; it'd be too
+  # easy to create an unstable studio.)
   for pkg in $pkgs; do
-    _hab install $pkg
+    if _hab install --channel="${CI_OVERRIDE_CHANNEL}" ${pkg}; then
```
Comment (schu) [inline components/studio/libexec/hab-studio-type-default.sh]:
```
if [[ -n "${CI_OVERRIDE_CHANNEL}" ]]; then
   _hab install --channel="${CI_OVERRIDE_CHANNEL}" ${pkg}
...
```

Would something like ^ work as well (instead of executing `_hab install ...` twice)? That would also avoid doubled log message:

```
» Installing core/hab-backline/0.51.0 from channel ''
» Installing core/hab-backline/0.51.0 from channel 'stable'
```

**Comment by schu** [comment]
I currently see another error when testing; the docker image build works but export fails silently:

```
[...]
worker.1    | DEBUG:habitat_builder_worker::runner::studio: completed studio build command, status=ExitStatus(ExitStatus(0))      
worker.1    | INFO:habitat_builder_worker::runner::studio: Airlock networking is not configured, skipping network destruction      
worker.1    | DEBUG:habitat_builder_worker::runner: Found runnable package, running docker export                                 
worker.1    | DEBUG:habitat_core::fs: resolved absolute path to program, program=dockerd, ident=core/docker, abs_path=/hab/pkgs/core/docker/17.09.0/20171001205930/bin/dockerd
worker.1    | DEBUG:habitat_builder_worker::runner::docker: building dockerd command, cmd="/hab/pkgs/core/docker/17.09.0/20171001205930/bin/dockerd" "-H" "unix:///hab/svc/builder-worker/data/886183870058242048/dockerd/var/run/docker.sock" "--pidfile" "/hab/svc/builder-worker/data/886183870058242048/dockerd/var/run/docker.pid" "--data-root" "/hab/svc/builder-worker/data/886183870058242048/dockerd/var/lib/docker" "--exec-root" "/hab/svc/builder-worker/data/886183870058242048/dockerd/var/run/docker" "--config-file" "/hab/svc/builder-worker/data/886183870058242048/dockerd/etc/daemon.json" "--group" "hab" "--iptables=false" "--ip-masq=false" "--ipv6=false" "--raw-logs"
worker.1    | DEBUG:habitat_builder_worker::runner::docker: setting docker export command env, PATH=/hab/pkgs/core/docker/17.09.0/20171001205930/bin
worker.1    | DEBUG:habitat_builder_worker::runner::docker: spawning dockerd export command                                       
worker.1    | DEBUG:habitat_core::fs: resolved absolute path to program, program=hab-pkg-export-docker, ident=core/hab-pkg-export-docker, abs_path=/hab/pkgs/core/hab-pkg-export-docker/0.51.0/20171218213726/bin/hab-pkg-export-docker
worker.1    | DEBUG:habitat_builder_worker::runner::docker: building docker export command, cmd=building docker export command, cmd="/hab/pkgs/core/hab-pkg-export-docker/0.51.0/20171218213726/bin/hab-pkg-export-docker" "--image-name" "<username-redacted>/zero-dep" "--base-pkgs-url" "http://localhost:9636" "--url" "http://localhost:9636" "--tag-latest" "--tag-version" "--tag-version-release" "--push-image" "--username" "<username-redacted>" "--password" "<password-redacted>" "--rm-image" "--registry-type" "docker" "/hab/svc/builder-worker/data/886183870058242048/out/<username-redacted>-zero-dep-0.1.0-20180102154015-x86_64-linux.hart"
worker.1    | DEBUG:habitat_builder_worker::runner::docker: setting docker export command env, DOCKER_HOST=unix:///hab/svc/builder-worker/data/886183870058242048/dockerd/var/run/docker.sock
worker.1    | DEBUG:habitat_builder_worker::runner::docker: spawning docker export command
worker.1    | DEBUG:habitat_builder_worker::runner::docker: completed docker export command, status=ExitStatus(ExitStatus(256))                                               
worker.1    | DEBUG:habitat_builder_worker::runner::docker: signaling dockerd to shutdown pid=20456, sig=TERM                                                                 
worker.1    | DEBUG:habitat_builder_worker::runner::docker: terminated dockerd                                                                                                
worker.1    | DEBUG:habitat_builder_worker::runner::log_pipe: completing log_forwarder, job_id=886183870058242048                  
jobsrv.1    | DEBUG:habitat_builder_jobsrv::server::log_ingester: Log complete for job 886183870058242048                                                                     
jobsrv.1    | DEBUG:habitat_builder_jobsrv::server::log_ingester: Archived log for job 886183870058242048                                                                     
worker.1    | DEBUG:habitat_builder_worker::runner: Failed studio build for schu/zero-dep, err=BuildFailure(1) 
```

Quite possible that it's unrelated to the changes above.

I'm not able to reproduce this from the command line, manually running the `dockerd` + `hab-pkg-export-docker` commands as shown in the log works.

**Comment by mwrock** [comment]
These errors may possibly be related to a last minute change made in response to some feedback on this PR that I did not rigorously test and was targeting that variable check. It was just a "style" comment and so I'm game to reverting it. I'll need to hunt down the original in the git log of my other computer. I'm out this week but should be able to hunt that down at some point soon.

File: components/studio/libexec/hab-studio-type-default.sh (hunk 2 above)
Comment (baumanj) [reply components/studio/libexec/hab-studio-type-default.sh]: Given that this may be sourced with `nounset` (aka `set -u`), changing to this should suffice:
```bash
if _hab install --channel="${CI_OVERRIDE_CHANNEL:-}" ${pkg}; then
    info "Override channel set; installed ${pkg} from ${CI_OVERRIDE_CHANNEL}"
else
    _hab install ${pkg}
fi
```
It will still result in the doubled log message (which may be useful diagnostics or noise depending on how you look at it). Compared to
```bash
if [[ -n "${CI_OVERRIDE_CHANNEL:-}" ]]; then
   _hab install --channel="${CI_OVERRIDE_CHANNEL}" ${pkg}
else
    _hab install ${pkg}
fi
```
there is a meaningful semantic difference. The first option will fall back to the default channel for `_hab install` whereas the second will cause the entire script to fail if the install with 
`CI_OVERRIDE_CHANNEL` fails. I'm not sure what the intention is.

**Comment by mwrock** [comment]
For now I'm reverting it to the code I tested against both the travis and the worker scenario. I can fiddle more with this when I'm back unless someone wants to carry it forward this week.

**Comment by schu** [comment]
> For now I'm reverting it to the code I tested against both the travis and the worker scenario.

Thanks, the current version (7531af6) works for me. Manully tested from a fresh install by cherry-picking and copying `components/studio/libexec/hab-studio-type-default.sh` after like

```
cp components/studio/libexec/hab-studio-type-default.sh /hab/pkgs/core/hab-studio/0.51.0/20171219022721/libexec/hab-studio-type-default.sh
```

File: support/ci/should_we_build.sh [hunk 3]
```diff
@@ -14,6 +14,12 @@ echo "======================================================="
 echo "Testing whether or not we need to build ${package_name}"
 echo "======================================================="
 
+hab pkg install core/rq
+hab pkg binlink core/rq rq
+
+hab pkg install core/jq-static
+hab pkg binlink core/jq-static jq
+
```
Comment (christophermaier) [inline support/ci/should_we_build.sh]: @mwrock Why did you need to add these? They should already be installed in `.travis.yml` (`jq` from Ubuntu packages, and `rq` from the [install_rq.sh](https://github.com/habitat-sh/habitat/blob/master/support/ci/install_rq.sh) script.

Also, this script is going to be run multiple times (once per package in the build), so we're going to be unnecessarily trying to install two Habitat packages each time.

Comment (mwrock) [reply support/ci/should_we_build.sh]: oh i can take that out. I added it because I hit issues locally (not in travis) but thats not really the use case for the deploy script.

**Comment by mwrock** [comment]
@christophermaier I removed the rq/jq installs

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/326532992).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/326532992).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265
