### PR TITLE
Fix studio exit

### LINKED ISSUE #1705: [bug] `hab studio rm` deletes files outside the studio
Last Friday I lost some data. `hab studio rm` removed not just the studio, but also all files in my working directory (including the .git directory)

### PR DESCRIPTION
**Pull request by nellshamrell**
Fixes #1705 

Agent Carter Go To Work

This makes it so that we unmount studio directories whenever someone exits the studio.  This should help reduce the times we see the bug where someone manually removes a studio directory (at /hab/studios) and it removes everything within the habitat directory (and sometimes parts of the user's workstation).  

There is still a possibility of this error happening if someone enters a studio, does not exit, and then manually removes the studio directory at /hab/studios.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

File: components/studio/bin/hab-studio.sh [hunk 1]
```diff
@@ -774,48 +774,7 @@ rm_studio() {
...
-  if $bb mount | $bb grep -q "on $HAB_STUDIO_ROOT/dev type"; then
-    $bb umount $v -l $HAB_STUDIO_ROOT/dev
-  fi
-
-  if $bb mount | $bb grep -q "on $HAB_STUDIO_ROOT/var/run/docker.sock type"; then
-    $bb umount $v -l $HAB_STUDIO_ROOT/var/run/docker.sock
-  fi
-
-  # Remove remaining filesystem
-  $bb rm -rf $v $HAB_STUDIO_ROOT
```
Comment (fnichol) [inline components/studio/bin/hab-studio.sh]: We'll want to keep the deletion of remaining Studio filesystem in the `hab-studio rm` subcommand and not in the generic cleanup as the current behavior of the Studio is to preserve your work between running `new`, `enter`, and `run` (`build` is the only subcommand which calls `hab-studio rm` at the beginning of its run).

**Comment by nellshamrell** [comment]
@fnichol done!

Good news is I was finally able to find the root cause of the issue - we were not deleting the studio/dev/null and studio/dev/console directories when exiting out of a studio, which is why it would delete the who filesystem when attempting to manually delete a studio's directory.  This will prevent it from doing that again!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/255804987).

**Comment by thesentinels** [comment]
:broken_heart: Travis CI reports [this PR failed to pass the test suite](https://travis-ci.org/habitat-sh/habitat/builds/255804987).

The next step is to examine the [job](https://travis-ci.org/habitat-sh/habitat/builds/255804987) and figure out why. If it is transient, you can try re-triggering the Travis CI Job - if it passes, this PR will be automatically merged. If it is not transient, you should fix the issue and update this pull request, and issue `approve` again. If you believe it will never pass, and you are feeling :godmode:, you can issue a `force` to merge this PR anyway.

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/255936649).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/255936649).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265
