### PR TITLE
Report errors when getting user and group

### LINKED ISSUE #7298: hab-sup erroneously reports missing group, fails to load service
On hab 0.90.6 (and possibly older), hab-sup can fail to start a service with the following error:

```
hab-sup(MR): Starting chef/deployment-service (chef/deployment-service/0.1.0/20191211163131)
hab-sup(MR): Can't create directory /hab/svc/deployment-service: Package requires group hab to exist, but it doesn't
hab-sup(MR): If this service is running as non-root, you'll need to create /hab/svc/deployment-service and give the curre...ccess to it
```

even when the `hab` group exists. This is because neither our code or the underlying library we use to get the group by name surfaces errors from `getgrnam_r`.

Our code always reports this error whenever the library returns None:

https://github.com/habitat-sh/habitat/blob/master/components/core/src/os/users/linux.rs#L77-L89

but the underlying library returns None in the case of an error:

https://github.com/ogham/rust-users/blob/master/src/base.rs#L484-L488

We've recently seen such an error occur because the user had an /etc/groups entry that was too large for the hard-coded buffer value of 2048 bytes. (I can provide a reproduction if you'd like to see the problem locally. Note that because of the way glibc's `getgrname` works, _any_ entry that precedes the entry you are looking for that requires a larger buffer will cause a failure.):

https://github.com/ogham/rust-users/blob/master/src/base.rs#L474

In our own code, we cannot simply check last_os_error() because the library does not give us access to the error code from the underlying system call. Since `errno` is not reset to 0 on success so we have no way to distinguish an error in this system call from an error in a previous system call on this thread.

While we could fix part of this upstream, completely fixing the problems with this call would require a breaking change to their library.  Namely, this api should have a return value of
`Result<Option<Group>>` rather than `Option<Group>`.

Alternatively, I think we should consider making the `nix` crate our default system-interface dependency for linux in any case where we don't want to call libc directly.  For instances, the nix version of this function already has the correct return value:

https://github.com/nix-rust/nix/blob/5cb526d55df223735602d2f50cae4c9b43120d9c/src/unistd.rs#L2724

and already handles buffer resizing:

https://github.com/nix-rust/nix/blob/5cb526d55df223735602d2f50cae4c9b43120d9c/src/unistd.rs#L2564-L2566

### PR DESCRIPTION
**Pull request by davidMcneil**
Resolves #7298 

This improves our APIs used to get users and groups by returning `Result<Option<T>>` instead of simply an `Option<T>`. This means we should now report an error instead of simply assuming there is no group in the case that the buffer is not large (or any other error). Users should then be able to increase the buffer size appropriately with the [`_SC_GETGR_R_SIZE_MAX` setting](https://github.com/nix-rust/nix/blob/96054b6933404b4c1d5dbd49db7ec7c7a26e44de/src/unistd.rs#L2707).

### CODE REVIEW

File: components/common/src/templating/config.rs [hunk 1]
```diff
@@ -613,10 +613,12 @@ mod test {
 
     fn curr_username() -> String {
         users::get_current_username().expect("Can get current username")
+                                     .expect("Can get current username")
```
Comment (christophermaier) [inline components/common/src/templating/config.rs:616]: I know this is a test helper function, but it would be good to make these `expect` messages different to help distinguish which operation failed, if one of them ever does.

I see a handful of other instances of this pattern elsewhere; same suggestion applies.

Comment (davidMcneil) [reply components/common/src/templating/config.rs]: Agreed. Addressed in https://github.com/habitat-sh/habitat/pull/7879/commits/1bd6407da4aecc1299a5ac0eef5ddcb0a9dbc46c

**Review by stevendanna — COMMENTED** [review]
:D You are much braver than I was.  Thanks for changing this API!
