### PR TITLE
[studio/docker] Drop `-ti` from Docker command when calling `hab pkg build`.

### LINKED ISSUE #3325: "the input device is not a TTY" on build
From my CI, it executes `hab pkg build .`:
```
* Error running command 'hab pkg build .': exit status 1. Output: 0.33.2: Pulling from studio
add3ddb21ede: Already exists
992b646baf01: Pulling fs layer
cf8121b68ad9: Pulling fs layer
4aa28c94fbdc: Pulling fs layer
cf8121b68ad9: Verifying Checksum
cf8121b68ad9: Download complete
992b646baf01: Verifying Checksum
992b646baf01: Download complete
992b646baf01: Pull complete
cf8121b68ad9: Pull complete
4aa28c94fbdc: Verifying Checksum
4aa28c94fbdc: Download complete
4aa28c94fbdc: Pull complete
Digest: sha256:fac838b632a83cc650019ca4f0ab9c560a35a55b662f47262c59a5ba4bdb2068
Status: Downloaded newer image for habitat-docker-registry.bintray.io/studio:0.33.2
the input device is not a TTY
```

@fnichol [4:49 PM] 
>Ah that makes sense. At the moment, we're always setting `--tty` when runing a studio call ([src](https://github.com/habitat-sh/habitat/blob/64ccc69ff07603d0df3ae278eac789a34e7b2636/components/hab/src/command/studio/docker.rs#L189)).

@johnjelinek [4:50 PM] 
> seems like `hab pkg build` should be an exception to setting `--tty`

### PR DESCRIPTION
**Pull request by fnichol**
This change changes the `docker run` arguments only when invoking the
`hab pkg build` subcommand. Specifically, the `--tty` and
`--interactive` flags are omitted for `build` but present for all other
`hab studio` invocations. This should help when `build` is called
non-interactively, such as in CI environments.

Closes #3325

tenor-143165879

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
tenor-134797427

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

File: components/hab/src/command/studio/docker.rs [hunk 1]
```diff
@@ -183,13 +183,14 @@ where
...
-    let mut cmd_args: Vec<OsString> = vec![
-        "run".into(),
-        "--rm".into(),
-        "--tty".into(),
-        "--interactive".into(),
-        "--privileged".into(),
-    ];
+    let mut cmd_args: Vec<OsString> = vec!["run".into(), "--rm".into(), "--privileged".into()];
+    match args.first().map(|f| f.to_str().unwrap_or_default()) {
+        Some("build") => {}
```
Comment (fnichol) [inline components/hab/src/command/studio/docker.rs]: @reset You know what I was after, right? Just could not find a much more elegant way to describe this. Seemed like `if let …` doesn't like `!=` bools.

Comment (reset) [reply components/hab/src/command/studio/docker.rs]: Yeah this was perfectly fine

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/280050861).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/280050861).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265
