### PR TITLE
Ensure that public and secret key exports always work

### LINKED ISSUE #2524: hab origin key export --type secret failure
hab origin key export can fail if there is a .pub key in the cache that is lexicographically higher rank than the secret key.

Eg - 
$ ls /hab/cache/keys/
core-20160612031944.sig.key  core-20160810182414.pub

$ sudo hab origin key export --type secret core
✗✗✗
✗✗✗ Crypto error: No secret key found at /hab/cache/keys/core-20160810182414.sig.key
✗✗✗

$ sudo RUST_LOG=debug hab origin key export --type secret core
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:hab: clap cli args: ["hab", "origin", "key", "export", "--type", "secret", "core"]
DEBUG:hab: remaining cli args: []
DEBUG:habitat_core::crypto::keys: checking file: core-20160810182414.pub
DEBUG:habitat_core::crypto::keys: valid key suffix
DEBUG:habitat_core::crypto::keys: checking file: core-20160612031944.sig.key
DEBUG:habitat_core::crypto::keys: valid key suffix
DEBUG:habitat_core::crypto::keys::sig_key_pair: Attempting to read key name_with_rev core-20160810182414 for core
DEBUG:habitat_core::crypto::keys::sig_key_pair: Can't find secret key for name_with_rev core-20160810182414: No such file or directory (os error 2)
DEBUG:habitat_core::crypto::keys::sig_key_pair: Attempting to read key name_with_rev core-20160612031944 for core
DEBUG:habitat_core::crypto::keys::sig_key_pair: Can't find public key for name_wi

### PR DESCRIPTION
**Pull request by raskchanky**
Previously, all you could do was ask for a list of keys, without being able to filter private and public keys separately.  This is totally fine if you always have matched public/private keys in your cache directory.  It caused problems, though, if you happen to be missing part of a key pair.

This whole flow of logic now takes an extra optional parameter for the `PairType` that lets you be specific about the key type you want.  All of the existing code that doesn't deal with key exporting that calls these functions passes `None`, meaning the existing behavior remains the same.  Origin key exporting utilizes the new parameter to filter keys based on the type of key you're trying to export.

Fixes #2524 

tenor-23759639

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

File: components/core/src/crypto/keys/mod.rs [hunk 1]
```diff
@@ -202,13 +207,35 @@ fn check_filename(keyname: &str, filename: String, candidates: &mut HashSet<Stri
...
+                }
+            }
+            Some(&PairType::Public) => {
+                if suffix == PUBLIC_KEY_SUFFIX {
+                    candidates.insert(thiskey);
+                }
+            }
+            None => {
+                candidates.insert(thiskey);
+                () // this feels gross but it was the only way to make the match arms the same
```
Comment (chefsalim) [inline components/core/src/crypto/keys/mod.rs]: maybe return a bool instead, and trigger the insert on the bool value?
eg - 
let do_insert = match pair_type {
   Some(&PairType::Secret) => expression,
   Some(&PairType::Public) => expression,
   None => true
};

**Comment by raskchanky** [comment]
@chefsalim I addressed your comment.  Thanks for the suggestion!

**Comment by chefsalim** [comment]
Looks good! 
tenor-92125744

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/247761368).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/247761368).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265
