### PR TITLE
Fixes wrongly listed conflicting versions

### LINKED ISSUE #4087: Dependency conflict detection sometimes include non conflicting packages
> hab 0.38.0/20171026215954

I noticed several times while building `core/glib` and friends that if a conflict is detected with different versions of `core/glib`, `core/glibc` got picked up too:

```
soup: Resolved dependency 'core/glib' to /hab/pkgs/core/glib/2.50.3/20171118162036
   soup: WARN 
   soup: WARN The following runtime dependencies have more than one version
   soup: WARN release in the full dependency chain:
   soup: WARN 
   soup: WARN   * core/glib ( core/glib/2.50.3/20171118162036 core/glib/2.50.3/20171118151949 core/glibc/2.22/20170513201042 )
```

### PR DESCRIPTION
**Pull request by rsertelon**
Should close #4087

Signed-off-by: Romain Sertelon <romain@sertelon.fr>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

File: components/plan-build/bin/hab-plan-build.sh [hunk 1]
```diff
@@ -1082,7 +1082,7 @@ _validate_deps() {
     warn "release in the full dependency chain:"
     warn
     echo "$dupes" | while read dupe; do
-      warn "  * $dupe ( $(echo "$tdeps" | grep "$dupe" | tr '\n' ' '))"
+      warn "  * $dupe ( $(echo "$tdeps" | grep "$dupe/" | tr '\n' ' '))"
```
Comment (christophermaier) [inline components/plan-build/bin/hab-plan-build.sh]: It might be more clear to grep for `"^${dupe}/"` instead. That will explicitly anchor the regex at the beginning of the identifier, and the `${...}` variable delimiter makes clear the distinction between the variable and the rest of the search string.

It took me a second to realize that the `/` character is the slash between the name and version of a fully-qualified identifier, and not a regular expression special character.

**Comment by rsertelon** [comment]
@christophermaier Done ;)

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/315521796).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265
