### PR TITLE
Corrects api_client response on hab bldr job start

### LINKED ISSUE #5694: Output of successful `hab bldr job start` looks failure-esqe
When I submit a job with `hab bldr job start` and the request succeeds, the output looks like something went wrong:

image

It should be greener and happier-looking. 💚

### PR DESCRIPTION
**Pull request by eeyun**
Fixes #5694 
Signed-off-by: Ian Henry <ihenry@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

File: components/builder-api-client/src/lib.rs [hunk 1]
```diff
@@ -398,7 +398,7 @@ impl Client {
         };
         match result {
             Ok(response) => {
-                if response.status == StatusCode::Ok {
+                if response.status == StatusCode::Created {
```
Comment (chefsalim) [inline components/builder-api-client/src/lib.rs]: Would be better to check for either Ok or Created in order to be backward compatible (on-prem instances running pre-Actix Builder)

Comment (eeyun) [reply components/builder-api-client/src/lib.rs]: Ah I was confused by what you meant by that. I'll get that added.
