### PR TITLE
sup: set PID file mode to 0644 

### LINKED ISSUE #7351: PID file permissions are wrong
I can't find any code related to set PID file permissions. So if service is running under the `hab` user I unable to read `PID` from `reconfigure` hook.

```
-rw-------  1 root root   5 Jan 21 11:30 PID
```

```
my-elasticsearch.default hook[reconfigure]:(HK): cat: can't open '/hab/svc/my-elasticsearch/PID': Permission denied
```

### PR DESCRIPTION
**Pull request by stevendanna**
Users currently expect to be able to read the PID file from their
runtime hooks. In 5734cce we started using atomic writer for the PID
file to avoid corruption, but this meant that the default mode for the
file became 0600.

Note: I've restricted this change to non-Windows systems. If anyone
knows of what our Window's users might expect, I'm happy to extend
this PR to include a change for Windows as well.

Fixes #7351

Signed-off-by: Steven Danna <steve@chef.io>

### CODE REVIEW

File: components/core/src/fs.rs [hunk 1]
```diff
@@ -719,6 +749,11 @@ impl AtomicWriter {
     /// temporary file to ensure all data is flushed to disk and then
     /// renaming the file into place.
     fn finish(self) -> io::Result<()> {
+        if let Some(permission) = self.permission {
+            set_permissions(&self.tempfile.path(), permission).map_err(|e| {
+                io::Error::new(io::ErrorKind::Other, e.to_string())
+            })?;
```
Comment (stevendanna) [inline components/core/src/fs.rs]: I don't love this.  We made a decision when creating the API to return an `io::Result<()>` here to make it easier on callers.  I don't have enough Rust experience to know if there is a better way to achieve the same ease of use so I'm happy to take whatever alternative y'all have (or just leave this bit of grossness).

File: components/core/src/fs.rs [hunk 2]
```diff
@@ -694,16 +709,34 @@ fn parent(p: &Path) -> io::Result<&Path> {
...
 /// Assumes that the parent directory of dest_path exists.
 pub struct AtomicWriter {
-    dest:     PathBuf,
-    tempfile: tempfile::NamedTempFile,
+    dest:       PathBuf,
+    tempfile:   tempfile::NamedTempFile,
+    #[cfg(not(windows))]
+    permission: Option<u32>,
+    #[cfg(windows)]
+    permission: Option<&[win_perm::PermissionEntry]>,
```
Comment (stevendanna) [inline components/core/src/fs.rs]: This doesn't actually work, it was just my first swing at what we might want to do, but for this to work I think we'll need some lifetime annotations.  If a reviewer things this is a useful feature for windows, I'll put some time into getting a cross-compilation setup going so I can develop the window's portions, otherwise, I'll make this PR posix-only for now since it is posix-only at the call-site.

File: components/core/src/fs.rs (hunk 1 above)
Comment (davidMcneil) [reply components/core/src/fs.rs]: You could implement `From<Error>` for `io::Error`

```rust
impl From<Error> for io::Error {
    fn from(e: Error) -> Self {
        io::Error::new(io::ErrorKind::Other, e.to_string())
    }
}
```

and then you would just need 
```rust
if let Some(permission) = self.permission {
    set_permissions(&self.tempfile.path(), permission)?;
}
```

You could even match on the `Error` type and try and convert it to the corresponding `io::Error` (`Error::PermissionFailed` to `io::Error::PermissionDenied`). But that just leads to the question, why does `set_permission` not use `io::Result`?

With all that said, the "correct" answer probably involves refactoring outside the scope of this PR so I am totally fine leaving it as is.

File: components/core/src/fs.rs (hunk 2 above)
Comment (stevendanna) [reply components/core/src/fs.rs]: I think a Vec<PermissionEntry> is probably the way to go here if we proceed with the windows stuff, thanks.

File: components/core/src/fs.rs [hunk 3]
```diff
@@ -443,13 +447,24 @@ impl<'a> SvcDir<'a> {
...
+    posix_perm::set_permissions(path.as_ref(), mode)
+}
+
+#[cfg(windows)]
+pub fn set_permissions<T: AsRef<Path>>(path: T,
+                                       entries: &[win_perm::PermissionEntry])
+                                       -> Result<()> {
+    win_perm::set_permissions(path.as_ref(), entries)
+}
+
```
[the remark this answers is not in the document]
Comment (stevendanna) [reply components/core/src/fs.rs]: 👍 I think this was the result of some iterative development on my part, originally these functions were doing a bit more but eventually they reduced to this and I didn't think to remove them.

File: components/core/src/fs.rs (hunk 1 above)
Comment (christophermaier) [reply components/core/src/fs.rs]: I think the "correct" answer lies in https://github.com/habitat-sh/habitat/issues/6557, but that is most assuredly outside the scope of this PR :smile: 

I'm OK with leaving this as-is for the time being.

**Comment by mwrock** [comment]
I think providing no windows implementation in the supervisor here is actually the right thing to do. By doing nothing, windows will simply allow the file to inherit the perms of the parent folder. We don't "harden" the `svc` folders (only some of their child folders so any authenticated user should have read access to the PID file on windows.

We should add a comment to this effect.

**Comment by stevendanna** [comment]
@mwrock Awesome, thanks!  I'll get this updated sometime this week.

**Comment by stevendanna** [comment]
I left the windows implementation of with_permissions in place just for symmetry, even though we aren't gonna use it for the PID file for now.
