### PR TITLE
uninstall should not rename to existing directory on windows

### LINKED ISSUE #6277: pkg uninstall broken on windows
On 0.77.0 and likely all versions since `hab pkg uninstall` was introduced, uninstalling a package on Windows results in:

```
C:\dev\habitat [sup_color]> hab pkg uninstall mwrock/blank1
» Uninstalling mwrock/blank1/0.1.0/20181212111157
☒ Deleting mwrock/blank1/0.1.0/20181212111157
✗✗✗
✗✗✗ Access is denied. (os error 5)
✗✗✗
```

### PR DESCRIPTION
**Pull request by mwrock**
fixes #6277. 

Uninstalling a package creates a temporary directory, renames the existing package directory to that temp directory and then deletes the temp directory. This unfortunately and rather unexpectedly is a classic case where unix and windows underlying IO operations differ.

The details are expressed in https://doc.rust-lang.org/std/fs/fn.rename.html but essentially given rust's rename implementation, you cannot rename a directory to an existing empty directory on Windows. On *nix you must rename to an existing empty directory.

The simplest fix is to just delete the newly created temp directory on windows. It just needs a path.

Signed-off-by: mwrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

File: components/hab/src/command/pkg/uninstall.rs [hunk 1]
```diff
@@ -217,7 +217,11 @@ fn do_clean_delete(pkg_root_path: &Path, real_install_path: &Path) -> Result<boo
     // below the pkg_root_path
     match real_install_path.parent() {
         Some(real_install_base) => {
+            // create empty temp directory
             let temp_install_path = temp_package_directory(real_install_path)?;
```
Comment (christophermaier) [inline components/hab/src/command/pkg/uninstall.rs]: When trying to find the `temp_package_directory` function, I noticed that the `use` statements at the top of this module are in separate "chunks" and also mix up a lot of external crate usage with internal usage.

While you're in here, it'd be a great cleanup opportunity!

File: components/hab/src/command/pkg/uninstall.rs [hunk 2]
```diff
@@ -217,7 +217,11 @@ fn do_clean_delete(pkg_root_path: &Path, real_install_path: &Path) -> Result<boo
...
+            // on windows fs::rename cannot rename to an existing directory even if empty
+            #[cfg(windows)]
+            fs::remove_dir(&temp_install_path)?;
```
Comment (christophermaier) [inline components/hab/src/command/pkg/uninstall.rs]: So, what we're really saying here is that we need `temp_package_directory` to provide us with a suitable _path_, rather than an actual directory, correct?

Since `temp_package_directory` returns a [TempDir](https://docs.rs/tempfile/3.0.7/tempfile/struct.TempDir.html), we may be able to take advantage of it's `Drop` behavior here. I'm thinking something like this:

```rust
let temp_install_path = {
    let td = temp_package_directory(real_install_path)?;
    td.into_path()
};
```

or, more succinctly:

```rust
 let temp_install_path = temp_package_directory(real_install_path)?.into_path();
```

That should end up removing the directory, and giving you the path you need, and it should be the same on both platforms.

Comment (mwrock) [reply components/hab/src/command/pkg/uninstall.rs]: but we only want to do that on windows. We actually do need the directory on linux. In that case I'm wondering if just the single platform constrained delete line is better.

Comment (christophermaier) [reply components/hab/src/command/pkg/uninstall.rs]: Unless I'm missing something, you don't actually need the empty directory on Linux in order to rename it.

```sh
maier@ubuntu:~/testing$ ls
test.rs
maier@ubuntu:~/testing$ cat test.rs 
use std::fs;

fn main() {
    fs::create_dir_all("foo").expect("couldn't create foo");
    fs::rename("foo", "bar").expect("couldn't rename to bar");
}
maier@ubuntu:~/testing$ rustc test.rs 
maier@ubuntu:~/testing$ ls
test  test.rs
maier@ubuntu:~/testing$ ./test
maier@ubuntu:~/testing$ ls
bar  test  test.rs
maier@ubuntu:~/testing$ ls -alh bar
total 8.0K
drwxr-xr-x 2 maier maier 4.0K Mar 20 16:04 .
drwxr-xr-x 3 maier maier 4.0K Mar 20 16:04 ..
maier@ubuntu:~/testing$ touch bar/blah
maier@ubuntu:~/testing$ ./test
thread 'main' panicked at 'couldn't rename to bar: Os { code: 39, kind: Other, message: "Directory not empty" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
maier@ubuntu:~/testing$ 

```

I think the docs are saying that if the `to` directory exists on Linux, it has to be empty.

Comment (mwrock) [reply components/hab/src/command/pkg/uninstall.rs]: oh ok. cool. I will try that!

Comment (mwrock) [reply components/hab/src/command/pkg/uninstall.rs]: Ended up that `into_path` "persists" the `TempDir` struct in which case its `drop` does not remove the file. However `path().to_path_buf()` accomplishes the same thing and does allow the `drop` to remove the directory. I validated this on both windows and linux.

Comment (christophermaier) [reply components/hab/src/command/pkg/uninstall.rs]: Oh, TIL 😄

File: components/hab/src/command/pkg/uninstall.rs [hunk 3]
```diff
@@ -217,7 +215,10 @@ fn do_clean_delete(pkg_root_path: &Path, real_install_path: &Path) -> Result<boo
     // below the pkg_root_path
     match real_install_path.parent() {
         Some(real_install_base) => {
-            let temp_install_path = temp_package_directory(real_install_path)?;
+            let temp_install_path = {
+                let td = temp_package_directory(real_install_path)?;
+                td.path().to_path_buf()
```
Comment (christophermaier) [inline components/hab/src/command/pkg/uninstall.rs]: We can make this a little simpler with:

```rust
let temp_install_path = temp_package_directory(real_install_path)?.path()
                                                                  .to_path_buf();

```
